apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: helm-goldilocks
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v1"
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: Installs the Fairwinds Goldilocks Helm chart for VPA recommendations.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # helm-goldilocks

    Installs the Fairwinds Goldilocks Helm chart using Crossplane and the Helm provider.
    Goldilocks helps you get resource requests "just right" with VPA recommendations.
  repository: ghcr.io/hops-ops/helm-goldilocks
  source: github.com/hops-ops/helm-goldilocks
