apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: Goldilocks
metadata:
  name: goldilocks
  namespace: default
spec:
  clusterName: production-cluster
  namespace: goldilocks
  labels:
    team: platform
    environment: production
  providerConfigRef:
    name: production-cluster
    kind: ProviderConfig
  values:
    # Dashboard settings
    dashboard:
      replicaCount: 2
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
    # Controller settings
    controller:
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
